package FE.SendData;


/**
* SendData/SendData_interfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SendData_interface.idl
* Saturday, April 9, 2022 4:31:42 o'clock PM EDT
*/

abstract public class SendData_interfaceHelper
{
  private static String  _id = "IDL:SendData/SendData_interface:1.0";

  public static void insert (org.omg.CORBA.Any a, SendData_interface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SendData_interface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SendData_interfaceHelper.id (), "SendData_interface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SendData_interface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SendData_interfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SendData_interface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SendData_interface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SendData_interface)
      return (SendData_interface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _SendData_interfaceStub stub = new _SendData_interfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SendData_interface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SendData_interface)
      return (SendData_interface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _SendData_interfaceStub stub = new _SendData_interfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
